# Generated by Django 3.2.9 on 2021-12-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='full_text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='preview_text',
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='text', verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Максимальная длина - 70 символов. Если вы не заполните это поле, оно будет сформировано автоматически', max_length=70, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='Максимальная длина - 100 символов. Если вы не заполните это поле, оно будет сформировано автоматически', max_length=100, verbose_name='URL'),
        ),
    ]
